name: "Set git config"
description: "Sets git config variables"
inputs:
  email:
    required: true
    description: "The email of the github account"

runs:
  using: "composite"
  steps:
    - name: Set git config
      shell: bash
      run: |
        git config --global user.email "${{ inputs.email }}"
        git config --global user.name "No Gravity Bot"
