name: On push workflow
on: push
jobs:
  install-and-build:
    uses: ./.github/workflows/install-and-build.yml

  unit-test:
    needs: install-and-build
    uses: ./.github/workflows/unit-test.yml

  publish:
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: [unit-test]
    uses: ./.github/workflows/publish.yml
    secrets: inherit
